# config/database.yml

development:
  adapter: postgresql
  encoding: unicode
  database: doberpop_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

test:
  adapter: postgresql
  encoding: unicode
  database: doberpop_test
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # On Render, DATABASE_URL comes from the linked Postgres service
  url: <%= ENV["DATABASE_URL"] %>